# Numpy Introduction

#### Import Numpy

In [1]:
import numpy as np

#### Zeroes - Create matrix with zero values

In [30]:
zeroes = np.zeros((3,4)) # (Rows,Cols,Depth)
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Ones - Initialized with one values

In [31]:
ones = np.ones((2,2)) # (Rows,Cols,Depth)
print(ones)

[[1. 1.]
 [1. 1.]]


#### Empty - Uninitialized array ( contains garbage values )

In [24]:
unknown = np.empty((2,2,2))
print(unknown)

[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 4.36754031e-321]
  [2.22521646e-306 1.86920871e-306]]]


#### Full - Initialized with values passed

In [23]:
data = np.array([[12,12],[14,14]])
print(data)

[[12 12]
 [14 14]]


### Random - different methods to initialize random values

#### 1) np.random.rand method

In [22]:
random1 = np.random.rand(3,2,4)
print(random1)

[[[0.30863867 0.95013486 0.80398575 0.92814576]
  [0.19307386 0.36823655 0.18746652 0.06552071]]

 [[0.24061622 0.74392426 0.69726849 0.40545642]
  [0.09640542 0.43570033 0.29784874 0.51377982]]

 [[0.1406678  0.7485966  0.71369352 0.15869283]
  [0.01999117 0.75272087 0.55773933 0.92035845]]]


#### 2) np.random.randint method

In [21]:
random2 = np.random.randint(0,10,size=(4,4)) #where it takes values from 0 to 10
print(random2)

[[7 0 5 2]
 [4 2 6 7]
 [2 6 1 3]
 [7 0 3 5]]


#### 3) Lin_Space - generate equally spaced numbers between start & stop values

In [20]:
lin = np.linspace(1,10,20)
print(lin)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### Accessing data

#### 1) Access all rows and all columns 

In [19]:
a = np.random.randint(0,10,size=(5,5))
a[:,:] #<--- All rows & Columns

array([[1, 7, 8, 0, 4],
       [3, 3, 4, 0, 2],
       [9, 1, 3, 0, 0],
       [7, 3, 7, 3, 2],
       [2, 6, 7, 8, 4]])

#### 2) First row but all columns 

In [27]:
a[0,:]

array([1, 7, 8, 0, 4])

#### 2) Perticular row but all columns 

In [28]:
a[[0,4,2],:]

array([[1, 7, 8, 0, 4],
       [2, 6, 7, 8, 4],
       [9, 1, 3, 0, 0]])

#### 3) All row but Perticular columns 

In [29]:
a[:,1:4]

array([[7, 8, 0],
       [3, 4, 0],
       [1, 3, 0],
       [3, 7, 3],
       [6, 7, 8]])

### Concatenation

* Axis = 0 means Vertical ( v )
* Axis = 1 means Horizontal ( > )
* Concatenate - join numpy array along provided axis
* Hstack - joining numpy array Horizontally
* Vstack - joining numpy array Vertically
* Hstack (rows, cols) Rows needed same in every array
* Vstack (rows, cols) Cols needed same in every array

### Spilitting

* Splits array into subarrays
* Split - Split the arrays as per axis mentioned
* Hsplit - This splits the horizontal axis
* Vsplit - This splits the vertical axis

In [56]:
aa = np.random.randint(0,10,size=(3,3))
bb = np.random.randint(10,20,size=(3,3))

Hstack = np.hstack([aa,bb])
Vstack = np.vstack([aa,bb])

print('First array aa ')
print(aa)

print('Second array bb ')
print(bb)

print('Horizontal Stacked array Hstack ')
print(Hstack)

print('Vertical Stacked array Vstack ')
print(Vstack)

First array aa 
[[1 8 4]
 [0 8 3]
 [9 9 8]]
Second array bb 
[[18 14 14]
 [15 11 11]
 [10 13 18]]
Horizontal Stacked array Hstack 
[[ 1  8  4 18 14 14]
 [ 0  8  3 15 11 11]
 [ 9  9  8 10 13 18]]
Vertical Stacked array Vstack 
[[ 1  8  4]
 [ 0  8  3]
 [ 9  9  8]
 [18 14 14]
 [15 11 11]
 [10 13 18]]


### Shape, Size, ndim

In [63]:
d = np.random.randint(0,10,size = (5,5))

In [64]:
d.ndim # Dimension of array

2

In [65]:
d.shape # Shape of array

(5, 5)

In [66]:
d.size # Size of array

25

### Reshaping

* Learning algorithms expects data in certain shape & dimension
* Using reshaping utility we can convert data into desired shape
* But, the desired transformation will also be of same size
* Adding 1 dimensions will not alter data size

In [69]:
z = np.random.randint(0,10,size = (4,8))
z

array([[5, 2, 6, 2, 3, 9, 1, 4],
       [6, 4, 3, 8, 4, 3, 5, 9],
       [6, 5, 4, 1, 3, 0, 8, 6],
       [5, 4, 3, 7, 9, 7, 3, 5]])

In [70]:
z = z.reshape((2,16))
z

array([[5, 2, 6, 2, 3, 9, 1, 4, 6, 4, 3, 8, 4, 3, 5, 9],
       [6, 5, 4, 1, 3, 0, 8, 6, 5, 4, 3, 7, 9, 7, 3, 5]])

### Utility Functions

Numpy has a huge list of mathematical functions to make implementing machine learning algorithms very easy A few of them are:

In [32]:
#max() <--- return max value of array
a.max()

9

In [33]:
#min() <--- return min value of array
a.min()

0

In [34]:
#mean() <--- return average value of array
a.mean()

3.76

In [35]:
#std() <--- return Standard Deviation of array
a.std()

2.7896953238660314

In [46]:
#dot() <---  return multiplication of two matrix
a = np.random.randint(0,10,size=(5,5))
b = np.random.randint(10,20,size=(5,5))
print('a---',a)
print('b---',b)
a.dot(b)

a--- [[4 6 8 6 4]
 [6 3 6 9 4]
 [5 9 5 3 9]
 [4 8 2 3 8]
 [5 6 9 7 3]]
b--- [[17 12 12 14 13]
 [18 12 10 17 17]
 [10 12 17 12 15]
 [12 18 16 16 10]
 [10 17 16 10 14]]


array([[368, 392, 404, 390, 390],
       [364, 410, 412, 391, 365],
       [423, 435, 427, 421, 449],
       [348, 358, 338, 344, 360],
       [397, 417, 433, 422, 414]])

In [47]:
#sqrt() <--- return square root of the each element of array
np.sqrt(a)

array([[2.        , 2.44948974, 2.82842712, 2.44948974, 2.        ],
       [2.44948974, 1.73205081, 2.44948974, 3.        , 2.        ],
       [2.23606798, 3.        , 2.23606798, 1.73205081, 3.        ],
       [2.        , 2.82842712, 1.41421356, 1.73205081, 2.82842712],
       [2.23606798, 2.44948974, 3.        , 2.64575131, 1.73205081]])

### Broadcasting

* Single row matrix are known as vectors
* Broadcasting is a technique using which Numpy does mathematical computation on data of different shapes & dimension
* We might need to reshape the data sometimes to enable broadcasting

Some example of broadcasting:

In [71]:
y = np.random.randint(1,5,size=(2,2))
print(y)
print('--------------')
y = y*2
print(y)

[[3 3]
 [1 1]]
--------------
[[6 6]
 [2 2]]


In [72]:
print(y)
print('--------------')
y[y>5]=5
print(y)

[[6 6]
 [2 2]]
--------------
[[5 5]
 [2 2]]


There are other lots of advance features in numpy array you can learn from numpy official website given below

https://numpy.org/doc/stable/user/quickstart.html